name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          make test-version
          make test
